### ISSUE TITLE
你好，代码运行有些问题请赐教

### ISSUE THREAD

**Issue by beam-fly** [WangGodder/deep-cross-modal-hashing#14]
FileNotFoundError: [Errno 2] No such file or directory: '/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/dataset/data/mirflckr25k/im1762.jpg'
我的代码运行出现了这个问题，但是我是按照说明下载解压的数据集，这是哪一步出了问题？望赐教，感谢！

**Comment by WangGodder** [comment]
那你就把缺失的文件放到这个路径下

**Comment by beam-fly** [comment]
你好我代码运行时的这个错误一直改不好，请问我是应该改config还是改哪部分代码呢？望赐教！谢谢！
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    run(config_path="/home/b3/demo_1/deep-cross-modal-hashing-master/default_config.yml")
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/run.py", line 42, in run
    get_train(method,data_name.upper(),img_dir,bit=bit, batch_size=batch_size, cuda=cuda, **kwargs)
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/run.py", line 51, in get_train
    train(dataset_name,img_dir, bit, **kwargs)
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/training/SCAHN.py", line 269, in train
    trainer.train()
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/training/SCAHN.py", line 169, in train
    self.valid(epoch)
  File "/home/b3/demo_1/deep-cross-modal-hashing-master/torchcmh/training/SCAHN.py", line 238, in valid
    return_hash=True)
ValueError: too many values to unpack (expected 6)
